name: Test00
on:
  push:

jobs: 
  build:
    name: Test00
    runs-on: ubuntu-latest
    steps:
    - name: Step01
      uses: actions/checkout@v2
    - name: Print directory structure
      # You may pin to the exact commit or the version.
      # uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@553df9b35280b89f01b0f3e4d93d9171095a55d4
      uses: AbAvramidis/XDTesting-Print-Directory-Structure@main


